CREATE TABLE `e_order_goods_cost` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`platform` varchar(255) DEFAULT NULL COMMENT '平台',
`orderPlatformType` varchar(255) DEFAULT NULL COMMENT '订单类型:sale,refund,resend',
`referenceNo` varchar(255) DEFAULT NULL COMMENT '订单号',
`platformReferenceNo` varchar(255) DEFAULT NULL COMMENT '平台订单号',
`receivingCode` varchar(255) DEFAULT NULL COMMENT '订单签出的入库单号',
`productId` varchar(255) DEFAULT NULL COMMENT '产品id',
`orderSaleType` varchar(255) DEFAULT NULL COMMENT '销售类型,0:标准 1:全额退款',
`siteId` varchar(255) DEFAULT NULL COMMENT '站点',
`sellerId` varchar(255) DEFAULT NULL COMMENT '卖家帐号',
`warehouseId` int(11) DEFAULT NULL COMMENT '发运仓库',
`productBarcode` varchar(255) DEFAULT NULL COMMENT '产品代码',
`opPlatformSalesSku` varchar(255) DEFAULT NULL COMMENT '平台销售SKU',
`opPlatformSalesSkuQuantity` int(255) DEFAULT NULL COMMENT '平台销售SKU数量',
`quantity` int(11) DEFAULT NULL COMMENT '数量',
`productTitle` varchar(255) DEFAULT NULL COMMENT '产品名称',
`orderTotalAmount` decimal(10,3) DEFAULT NULL COMMENT '订单总金额(包含客户运费、平台补贴)',
`productAmount` decimal(10,3) DEFAULT NULL COMMENT '商品总金额',
`buyerPayShipping` decimal(10,3) DEFAULT NULL COMMENT '平摊平台运费',
`ebaySellerRebate` decimal(10,3) DEFAULT NULL COMMENT '平摊平台补贴',
`shippingFee` decimal(10,3) DEFAULT NULL COMMENT '平摊派送运费',
`paymentPlatformFee` decimal(10,3) DEFAULT NULL COMMENT '平摊paypal手续费',
`platformCost` decimal(10,3) DEFAULT NULL,
`fbaFee` decimal(10,3) DEFAULT NULL COMMENT '平摊fba费用',
`packageFee` decimal(10,3) DEFAULT NULL COMMENT '包材费用',
`warehouseStorageCharges` decimal(10,3) DEFAULT NULL COMMENT '仓租',
`processingFee` decimal(10,3) DEFAULT NULL COMMENT '处理费',
`otherFee` decimal(10,3) DEFAULT NULL COMMENT '平摊其它费用',
`purchaseShippingFee` decimal(10,3) DEFAULT NULL COMMENT '采购运费',
`purchaseTaxationFee` decimal(10,3) DEFAULT NULL COMMENT '采购税费',
`purchaseCost` decimal(10,3) DEFAULT NULL COMMENT '采购成本',
`serviceTransportFee` decimal(10,3) DEFAULT NULL COMMENT '第三方派送费',
`currency_rate` decimal(10,3) DEFAULT NULL COMMENT '汇率',
`pay_time` datetime DEFAULT NULL COMMENT '付款时间',
`updateTime` datetime DEFAULT NULL COMMENT '更新时间',
`referencePrice` decimal(10,3) DEFAULT NULL COMMENT '参考单价',
`avgUnitPrice` decimal(10,3) DEFAULT NULL COMMENT '平均单价',
`avgPurchasePrice` decimal(10,3) DEFAULT NULL COMMENT '平均采购价',
`firstCarrierFreight` decimal(10,3) DEFAULT NULL COMMENT '头程运费成本',
`tariffFee` decimal(10,3) DEFAULT NULL COMMENT '头程关税成本',
`orderTotalAmountOrg` decimal(10,3) DEFAULT NULL COMMENT '订单总金额(包含客户运费、平台补贴)（原币种）',
`productAmountOrg` decimal(10,3) DEFAULT NULL COMMENT '商品总金额（原币种）',
`buyerPayShippingOrg` decimal(10,3) DEFAULT NULL COMMENT '平摊平台运费（原币种）',
`shippingFeeOrg` decimal(10,3) DEFAULT NULL,
`paymentPlatformFeeOrg` decimal(10,3) DEFAULT NULL COMMENT '平摊paypal手续费（原币种）',
`platformCostOrg` decimal(10,3) DEFAULT NULL COMMENT '平摊平台手续费（原币种）',
`fbaFeeOrg` decimal(10,3) DEFAULT NULL COMMENT '平摊fba费用（原币种）',
`packageFeeOrg` decimal(10,3) DEFAULT NULL COMMENT '包材费用（原币种）',
`warehouseStorageChargesOrg` decimal(10,3) DEFAULT NULL COMMENT '仓租（原币种）',
`avgUnitPriceOrg` decimal(10,3) DEFAULT NULL COMMENT '平均单价（原币种）',
`processingFeeOrg` decimal(10,3) DEFAULT NULL COMMENT '处理费（原币种）',
`otherFeeOrg` decimal(10,3) DEFAULT NULL COMMENT '平摊其它费用（原币种）',
`ebaySellerRebateOrg` decimal(10,3) DEFAULT NULL COMMENT '平摊平台补贴（原币种）',
`currencyCodeOrg` decimal(10,3) DEFAULT NULL COMMENT '原币种',
`currencyCode` decimal(10,3) DEFAULT NULL COMMENT '转换币种',
`totalCost` decimal(10,3) DEFAULT NULL COMMENT '总成本',
`grossProfit` decimal(10,3) DEFAULT NULL COMMENT '毛利',
`grossProfitRate` decimal(10,3) DEFAULT NULL COMMENT '毛利率',
`factoryGrossProfit` decimal(10,3) DEFAULT NULL COMMENT '工厂毛利',
`factoryGrossMargin` decimal(10,3) DEFAULT NULL COMMENT '工厂毛利率',
`asinOrItem` varchar(255) DEFAULT NULL COMMENT 'amazon asin码(eBay ItemID)',
`destinationCountry` varchar(255) DEFAULT NULL COMMENT '目的国家',
`dateRelease` datetime DEFAULT NULL COMMENT '审核时间',
`soShipTime` datetime DEFAULT NULL COMMENT '发货时间',
`developResponsibleName` varchar(255) DEFAULT NULL COMMENT '开发员',
`sellerResponsibleName` varchar(255) DEFAULT NULL COMMENT '销售负责人',
`buyerName` varchar(255) DEFAULT NULL COMMENT '采购负责人',
PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4;

